### ISSUE TITLE
How  to  run

### ISSUE THREAD

**Issue by ZYF12138-zyf** [D-X-Y/AutoDL-Projects#101]
Man, how to run it? Help! The teacher found your code on GitHub as our final evaluation. The teacher was irresponsible and didn't teach us python. Help me！

**Comment by D-X-Y** [comment]
This repo contains multiple NAS algorithms. Which one do you prefer to running? If you have no preference, I would recommend NATS-Bench. In this case, please have a look at https://github.com/D-X-Y/AutoDL-Projects/tree/main/exps/NATS-algos and our paper (https://arxiv.org/abs/2009.00437).

**Comment by ZYF12138-zyf** [comment]
Could you please tell me which one is easier to operate? Could you please recommend one or two algorithms that are easier to understand？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月6日(星期四) 晚上8:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [D-X-Y/AutoDL-Projects] How  to  run (#101)






这个repo包含多个NAS算法。比起跑步，你更喜欢哪一种？如果你没有偏好，我会推荐NATS-Bench。在这种情况下，请您看看https://github.com/D-X-Y/AutoDL-Projects/tree/main/exps/NATS-algos而我们的论文（https://arxiv.org/abs/2009.00437).

—
您正在接收此消息，因为您编写了线程。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by D-X-Y** [comment]
NATS-Bench is easier to run.
Commands are listed in the comments in each file under this folder: https://github.com/D-X-Y/AutoDL-Projects/tree/main/exps/NATS-algos

**Comment by ZYF12138-zyf** [comment]
Thank you, Sir, I am not engaged in this industry after graduation, but your kindness today, let me have the idea of engaged in this field, thank you, I wish you a happy life and a successful career!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月6日(星期四) 晚上8:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [D-X-Y/AutoDL-Projects] How  to  run (#101)






NATS-Bench更容易运行。
此文件夹下每个文件的注释中列出了命令：https://github.com/D-X-Y/AutoDL-Projects/tree/main/exps/NATS-algos

—
您正在接收此消息，因为您编写了线程。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by D-X-Y** [comment]
You are welcome, I'm glad it helps!
