### ISSUE TITLE
Permission denied (publickey)... Error when cloning repo

### ISSUE THREAD

**Issue by FarahSaeed** [D-X-Y/AutoDL-Projects#105]
Hi,

I am trying to download the repo using following lines.

```
git clone --recurse-submodules git@github.com:D-X-Y/AutoDL-Projects.git XAutoDL
git clone --recurse-submodules https://github.com/D-X-Y/AutoDL-Projects.git XAutoDL

```

However it shows this error when I run the first line.

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I have tried on both Windows and Linux. It shows this error on both.

Thanks!

**Comment by D-X-Y** [comment]
Let me have a try, will reply soon.

**Comment by D-X-Y** [comment]
@FarahSaeed does "git clone https://github.com/D-X-Y/AutoDL-Projects.git XAutoDL" work on your machine?

**Comment by D-X-Y** [comment]
Sorry for the misleading README, "git clone --recurse-submodules https://github.com/D-X-Y/AutoDL-Projects.git XAutoDL" should work now.

**Comment by FarahSaeed** [comment]
Thank you so much. It is working now.
