### ISSUE TITLE
ModuleNotFoundError: No module named 'nas_201_api'

### ISSUE THREAD

**Issue by FarahSaeed** [D-X-Y/AutoDL-Projects#107]
Hi!

I am trying to run DARTS following instructions from 
https://github.com/D-X-Y/AutoDL-Projects/blob/main/docs/ICLR-2019-DARTS.md

As ./scripts-search/algos/DARTS-V2.sh was not present so I used 

./scripts-search/NAS-Bench-201-algos/DARTS-V2.sh.

After that, when I run this command

 `CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/NAS-Bench-201-algos/DARTS-V2.sh cifar10 1 -1`

It shows this 
```
script name: ./scripts-search/NAS-Bench-201-algos/DARTS-V2.sh
3 arguments
Traceback (most recent call last):
  File "./exps/NAS-Bench-201-algos/DARTS-V2.py", line 24, in <module>
    from nas_201_api import NASBench201API as API
ModuleNotFoundError: No module named 'nas_201_api'
```

Can you share where I might be mistaken.

Thanks!

**Comment by D-X-Y** [comment]
You can install nas_201_api via `pip install nas-bench-201`

**Comment by FarahSaeed** [comment]
Thank you very much. This error resolved after pip install nas-bench-201.

**Comment by D-X-Y** [comment]
Good to know that! By the way, `NAS-Bench-201` was upgraded to `NATS-Bench`. I would suggest use the new `NATS-Bench` (https://github.com/D-X-Y/AutoDL-Projects/tree/main/exps/NATS-algos) to run different baselines. The codes are very similar to that in NAS-Bench-201, but optimized better.

**Comment by FarahSaeed** [comment]
Thank you very much for this information!
