### ISSUE TITLE
NATS-Bench

### ISSUE THREAD

**Issue by guochengqian** [D-X-Y/AutoDL-Projects#109]
**Describe the Question**
Hi all, thanks for the amazing work. I have some small questions needs your clarification:
1. seems NATS-Bench is more recommended than NAS-Bench-201. Are they two different benchmarks or just the same benchmarks but organized in different ways? 
2.  Could you write a clear instruction how to use NATS-Bench if it is recommended? there is not readme file for it. like where should I find `NATS-tss-v1_0-3ffb9-simple` 

thank you!

**Comment by guochengqian** [comment]
for the second question, one can get the instruction from another repo (https://github.com/D-X-Y/NATS-Bench) by @D-X-Y

**Comment by D-X-Y** [comment]
Hi, thanks for your questions. I decoupled the NATS-Bench codes from AutoDL-Projects.

Here are a brief intro on how to run different NAS algorithms on `NATS-Bench` (https://github.com/D-X-Y/AutoDL-Projects/tree/main/exps/NATS-algos). At the top of each individual file, you will find more explanations and off-the-shelf commands.

**Comment by guochengqian** [comment]
thank you!
