### ISSUE TITLE
About the TORCH_HOME

### ISSUE THREAD

**Issue by ZhangYutongRose** [D-X-Y/AutoDL-Projects#111]
Where shall I set the TORCH_HOME?
I have set the TORCH_HOME in bashrc like this:
export TORCH_HOME="/home/yutong.zhang/dataset/"
but the system warned me "Must set TORCH_HOME envoriment variable for data dir saving"

**Comment by D-X-Y** [comment]
Can you have a try to "echo $TORCH_HOME" to see whether your bashrc command is activated?
I just put this line in my .bashrc or .zshrc, if your bashrc is loaded then I think it should be fine.

**Comment by ZhangYutongRose** [comment]
> Can you have a try to "echo $TORCH_HOME" to see whether your bashrc command is activated? I just put this line in my .bashrc or .zshrc, if your bashrc is loaded then I think it should be fine.

thanks

**Comment by D-X-Y** [comment]
Feel free to reopen the issue if you still have this issue.
