### ISSUE TITLE
About Sequential Greedy Architecture Search (SGAS)

### ISSUE THREAD

**Issue by Tommy787576** [D-X-Y/AutoDL-Projects#112]
**Which Algorithm**
Sequential Greedy Architecture Search (SGAS)

**Describe the Question**
Hi! First of all, thank you for your great work!
I'm curious that if this benchmark is suitable for SGAS:
https://arxiv.org/abs/1912.00195
or PC-DARTS:
https://arxiv.org/abs/1907.05737
Besides, which kinds of DARTS-based searching method are suitable for this benchmark?

Great Thanks!

**Comment by D-X-Y** [comment]
Good question. As long as these NAS algorithms are applicable to any search space, they can use NATS-Bench / NAS-Bench-201.
Based on my understanding of these two works, these two works can use our benchmark, while it requires to re-implement the super-model in this repo based on their algorithms.

**Comment by Tommy787576** [comment]
Thank you!
