### ISSUE TITLE
 The link of NAS-BENCH-201-4-v1.0-archive.tar failed

### ISSUE THREAD

**Issue by xiayouran** [D-X-Y/AutoDL-Projects#116]
**Which Algorithm**
NAS-Bench-201

**Describe the Question**
hello, the link of NAS-BENCH-201-4-v1.0-archive.tar failed. Can you upload it again? thanks.
![image](https://user-images.githubusercontent.com/45480822/157657815-609d028f-1522-4105-b878-2213d38c08b6.png)

**Comment by D-X-Y** [comment]
Thanks for your interest in our benchmark. That checkpoints are deprecated.
I would suggest you use our latest benchmark (NATS-Bench, https://github.com/D-X-Y/NATS-Bench), where NAS-Bench-201 is just a subset of it.

The full checkpoints (including weights) can be found at https://github.com/D-X-Y/NATS-Bench#preparation-and-download

**Comment by xiayouran** [comment]
Thank you for your reply. I see :ok_hand: , thanks
