### ISSUE TITLE
How to quickly retrain network architecture from scratch after getting the best topology

### ISSUE THREAD

**Issue by xielinzhen** [D-X-Y/AutoDL-Projects#117]
python ./exps/NATS-algos/search-cell.py --dataset cifar10  --data_path $TORCH_HOME/cifar.python --algo darts-v1 --rand_seed 777

With the above commands, I have the best topology(|nor_conv_1x1~0|+|none~0|none~1|+|nor_conv_3x3~0|nor_conv_1x1~1|none~2|),

How do I train this topology from scratch？

**Comment by D-X-Y** [comment]
For the NATS-bench, it does not need to re-train it from scratch, as you can easily query the re-training performance via NATS-Bench API, see https://github.com/D-X-Y/NATS-Bench

**Comment by xielinzhen** [comment]
> For the NATS-bench, it does not need to re-train it from scratch, as you can easily query the re-training performance via NATS-Bench API, see https://github.com/D-X-Y/NATS-Bench And see examples in our code: https://github.com/D-X-Y/AutoDL-Projects/blob/main/exps/NATS-algos/search-cell.py#L727

Thanks for your reply and your great work!
