### ISSUE TITLE
Where can I get the code for regularized_ea train and evaluation

### ISSUE THREAD

**Issue by xielinzhen** [D-X-Y/AutoDL-Projects#118]
**Which Algorithm**
regularized_ea

**Describe the Question**
python ./exps/NATS-algos/regularized_ea.py --dataset cifar10 --search_space tss --ea_cycles 200 --ea_population 10 --ea_sample_size 3 --rand_seed 1
I would like to execute the above command to get the time and accuracy of the actual training evaluation on my own device,  but there is only simulation training and evaluation,
[https://github.com/D-X-Y/AutoDL-Projects/blob/main/exps/NATS-algos/regularized_ea.py#L172](https://github.com/D-X-Y/AutoDL-Projects/blob/main/exps/NATS-algos/regularized_ea.py#L172)

where can I get the code for the actual training evaluation

**Comment by D-X-Y** [comment]
Good question!

The actual training and evaluation codes, which are used when I built this benchmark, is at: https://github.com/D-X-Y/AutoDL-Projects/blob/main/exps/NATS-Bench/main-tss.py#L37.
However, if you want to integrate it with the REA algorithm, you need to modify the function in `main-tss.py` and replace the simulate_train_eval call with the modified function.

**Comment by xielinzhen** [comment]
> Thanks for your reply
