### ISSUE TITLE
failed to download NAS-Bench-201-v1_1-096897.pth 

### ISSUE THREAD

**Issue by DoctorLiQ** [D-X-Y/AutoDL-Projects#120]
Said to be unauthentic to download.

**Comment by D-X-Y** [comment]
Doesn't this link (https://drive.google.com/file/d/16Y0UwGisiouVRxW-W5hEtbxmcHw_0hF_/view?usp=sharing) work?

**Comment by D-X-Y** [comment]
I just tried through a different account and it works

**Comment by D-X-Y** [comment]
Feel free to re-open it if you still have the same permission issue.
