### ISSUE TITLE
Loading weights for NAS-Bench 201

### ISSUE THREAD

**Issue by sumegha1024** [D-X-Y/AutoDL-Projects#124]
Hi, I am using the newer version of the NAS bench 201 API - NAS-Bench-201-v1_1-096897.pth and am trying to reload model and weights based on the architecture index. The pth file doesn't contain the trained weight information. 

In the description you mentioned that, 
"The latest benchmark file of NAS-Bench-201 (NAS-Bench-201-v1_1-096897.pth) can be downloaded from google drive.The files for model weight are too large (431G) and I need some time to upload it."

I am not able to find the corresponding uploaded files for model weight. Did you manage to upload them yet?

If not, should i use the older version [NAS-BENCH-201-4-v1.0-archive.tar] or would there be an issue with using the deprecated version to load model weights?

Thanks!

**Comment by sumegha1024** [comment]
As a follow up I tried downloading the [NAS-BENCH-201-4-v1.0-archive.tar] file to get the weights but it says the url is not available.

**Comment by shashankskagnihotri** [comment]
Hi, is there an update on this?

**Comment by sumegha1024** [comment]
If i remember correctly you need to use the newer NATS bench repository to access trained weights. https://github.com/D-X-Y/NATS-Bench

**Comment by shashankskagnihotri** [comment]
Perfect, thanks :)

**Comment by D-X-Y** [comment]
+1 Please refer to https://github.com/D-X-Y/NATS-Bench for the up-to-date model weights.
