### ISSUE TITLE
Can you release the searched model of ImageNet ?

### ISSUE THREAD

**Issue by tuanhui-li** [D-X-Y/AutoDL-Projects#48]
I want to use your searched model for study, can you release the finnal model checkpoints of ImageNet in Table 3 of your paper, or the searched model configirations, both will be ok, thanks !

**Comment by D-X-Y** [comment]
@tuanhui-li  Would you mind to indicate which paper? This repo contains multiple searching algorithms.

**Comment by tuanhui-li** [comment]
Oh, I mean the paper of 'Network Pruning via Transformable Architecture Search', in [`configs/NeurIPS-2019`](https://github.com/D-X-Y/NAS-Projects/tree/master/configs/NeurIPS-2019), where only contains the model config of CIFAR-X. Can you share the model config of ImageNet and the final checkpoints reported on Table 3 of the original paper ? Thanks .

**Comment by D-X-Y** [comment]
@tuanhui-li Thanks for your interests. I will upload the configs in 24 hours. Currently, I'm largely re-organizing the codes and can not push those configs right now, sorry for the inconvenience.
Regarding the final checkpoints, I find some of them in my server and will upload them soon, but some checkpoints are lost. Thanks for your patience.

**Comment by tuanhui-li** [comment]
@D-X-Y Maybe you can also provide the shell scripts for ImageNet model searching and inference, which will be much helpful. I think these hyper-parameters for ImageNet are different from the CIFARX, and the results on ImageNet are much more important.

**Comment by D-X-Y** [comment]
@tuanhui-li Sure, please see the following updates:
- ImageNet configs at https://github.com/D-X-Y/AutoDL-Projects/tree/master/configs/NeurIPS-2019
- I double-checked the log and script, I fixed the config-path for ImageNet (details at https://github.com/D-X-Y/AutoDL-Projects/blob/master/scripts/tas-infer-train.sh#L32)
- Logs for searching and training(you-called-inference) on CIFAR: https://drive.google.com/open?id=1h0RPrbXL-79U-CBos1wOst60oNxOkrWS
- Logs for training the searched shape of ResNet-18 on ImageNet:  https://drive.google.com/open?id=1FTXnbKnOcwsKVCQvNUgU6RVqYtRiiHMw
- Logs for training the searched shape of ResNet-50 on ImageNet:  https://drive.google.com/open?id=1TwCBgbFzGGMbdglLWJQPyMZgIm9acRaz
- I did not find the searching log of ImageNet on my current server. I will try to look at other devices.

Hope my codes and checkpoints are useful to you :)

**Comment by tuanhui-li** [comment]
@D-X-Y I am sorry to bother you again ! Can you release the script for searching imagenet model ?

**Comment by haolibai** [comment]
Hi, I am also looking forward to search scripts of ResNet 18/50 on Imagenet dataset. Thank you very much!

**Comment by D-X-Y** [comment]
Sorry for the late reply. I will try to find
