### ISSUE TITLE
setname: x-valid and ori-test

### ISSUE THREAD

**Issue by semin-park** [D-X-Y/AutoDL-Projects#52]
In order to use the `.get_metrics()` API, I need to put in the name of the dataset as well as the "setname". What is this exactly?

There seem to be 'train', 'x-valid', 'x-test' and 'ori-test, but there doesn't seem to be any documentation on what they are.

I would like to get the test performance of an architecture on all tested datasets (that is cifar10, cifar100 and imagenet16-120). Which setnames should I then use?

**Comment by D-X-Y** [comment]
@semin-park  Sorry for the misleading args...
I just added some necessary comments for get_metrics, please see them at here (https://github.com/D-X-Y/AutoDL-Projects/blob/master/lib/nas_201_api/api.py#L369). Does it answer your questions? Please feel free to ask if you have further questions.

**Comment by ultmaster** [comment]
One follow-up question:

Here, ori-test in cifar10-valid is "validation + test" (25000 + 10000 if I'm right):

https://github.com/D-X-Y/AutoDL-Projects/blob/25e529f788f1f66903ea34f720e702ee48ddcc69/lib/nas_201_api/api.py#L422

But the code seems to disagree here. It says ori-test is only valid_data, which is 10000 images.

https://github.com/D-X-Y/AutoDL-Projects/blob/25e529f788f1f66903ea34f720e702ee48ddcc69/exps/NAS-Bench-201/main.py#L49

**Comment by D-X-Y** [comment]
@ultmaster Thanks a lot for your careful check. It is my mistake and I just fixed it. Thanks again.
