### ISSUE TITLE
The search results of DARTS

### ISSUE THREAD

**Issue by GongXinyuu** [D-X-Y/AutoDL-Projects#58]
Hi, thanks for your great work! However, I found something strange when I use your code to search.

**Describe the bug**
The search result of DARTS is a combination of skip_connect.

**To Reproduce**
Just run:
```
CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/algos/DARTS-V1.sh cifar10 1 -1
CUDA_VISIBLE_DEVICES=1 bash ./scripts-search/algos/DARTS-V2.sh cifar10 1 -1
```
Python version: 3.6, PyTorch version: 1.4.0

**Screenshots**
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/20336084/76448899-1b74b180-6399-11ea-8753-8424a46f54be.png">

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/20336084/76448778-ec5e4000-6398-11ea-9436-4f769d30d06d.png">

**Comment by D-X-Y** [comment]
That is the expected results and has been discussed in our ICLR 2020 paper (https://openreview.net/forum?id=HJxyZkBKDr). In short, DARTS is easy to converge to a network with many skip connection layers, which has also been found by many other papers.
