### ISSUE TITLE
[NAS-bench-201] Questions of applying GDAS on CIFAR-100

### ISSUE THREAD

**Issue by GongXinyuu** [D-X-Y/AutoDL-Projects#64]
Hi Xuanyi,
Thanks for your great work! I've encountered some problems when I try to reproduce the result. I'd really appreciate it if you can spare some time on it.

**Describe the bug**
Cannot reproduce the search result of GDAS on CIFAR100

**To Reproduce**
```
bash ./scripts-search/algos/GDAS.sh cifar100 1 777
bash ./scripts-search/algos/GDAS.sh cifar100 1 888
bash ./scripts-search/algos/GDAS.sh cifar100 1 999
```
Ubuntu, Python 3.6, pytorch 1.4.0

**Expected behavior**
Should match the number reported in the paper.

**Screenshots**
I run the script many times, but I got the best accuracy of 67.56 on CIFAR-100. The number is obtained on 'ori-test' set.

**Comment by D-X-Y** [comment]
In our NAS-Bench-201 paper, we searched on CIFAR-10, and report the results of CIFAR-10 searched architecture on three datasets. We did not do the above experiments in our paper.

**Comment by GongXinyuu** [comment]
Thanks for your prompt clarification!
