### ISSUE TITLE
[TAS] Question about resnet basicblock architecture.

### ISSUE THREAD

**Issue by kwonbeomseok** [D-X-Y/AutoDL-Projects#65]
Thank you for your great work and sharing code.

I have a question about ResNet basicblock. 
https://github.com/D-X-Y/AutoDL-Projects/blob/569b9b406ae8331fbbb130c97be35f0a9f313abf/lib/models/shape_searchs/SearchCifarResNet_width.py#L159
There is no activation function(Relu) output of basicblock in search forward. Is there a reason you didn't put it in?

**Comment by D-X-Y** [comment]
Nice catch. It should be a bug. Thanks for pointing out!

**Comment by D-X-Y** [comment]
@kwonbeomseok I just push a new commit to fix this issue: https://github.com/D-X-Y/AutoDL-Projects/tree/076f9c2d41dc888b8087c266261d2094c8739340

Please let me know if you have further questions.
