### ISSUE TITLE
DARTS1V-search-NASNet-space.sh how to interpret results

### ISSUE THREAD

**Issue by abduallahmohamed** [D-X-Y/AutoDL-Projects#66]
Hi, sorry for asking too much

I ran bash -i ./scripts-search/DARTS1V-search-NASNet-space.sh cifar10 -1 and got the log and .pth file,
is there a script I need to run so I can tell exactly what's the architecture I found?

Thanks

**Comment by abduallahmohamed** [comment]
I think I resolved it ! thanks

**Comment by abduallahmohamed** [comment]
I'm sorry about this but I do have hard time trying to draw the cell generated from the search, for instance: 
how would this looks like?
`['|nor_conv_3x3~0|+|nor_conv_3x3~0|nor_conv_3x3~1|+|skip_connect~0|skip_connect~1|skip_connect~2|' ]`
as a cell? 
![image](https://user-images.githubusercontent.com/22107547/83377609-9dd3a700-a3c5-11ea-8f04-bd1b6b20ad67.png)
does this looks right?

**Comment by D-X-Y** [comment]
For `|nor_conv_3x3~0|+|nor_conv_3x3~0|nor_conv_3x3~1|+|skip_connect~0|skip_connect~1|skip_connect~2|`, it will be parsed as follows:
```
node-1 = nor_conv_3x3(node-0, i.e., inputs)
node-2 = nor_conv_3x3(node-0) + nor_conv_3x3(node-1)
node-3 = node-0 + node-1 + node 2
```
Yeap, your figure looks correct.
