### ISSUE TITLE
how to train model found by DARTS1V-search-NASNet-space.sh

### ISSUE THREAD

**Issue by abduallahmohamed** [D-X-Y/AutoDL-Projects#67]
Hi, 

I read most of the issues with how to train and so, I reached out that I might need to use:  
`./scripts/nas-infer-train.sh cifar10` to train the model, but apparently there's no such thing as ./configs/archs/NAS-CIFAR-DARTS_V1.config

Am I missing something? 

Thanks

**Comment by D-X-Y** [comment]
Please see README here: https://github.com/D-X-Y/AutoDL-Projects/blob/master/docs/CVPR-2019-GDAS.md#searching-on-the-nasnet-search-space

It is suggested to use `./scripts/retrain-searched-net.sh` to re-train the searched architecture.
