### ISSUE TITLE
Request for log files of 10 different searching algorithms in your NAS-Bench-201 paper

### ISSUE THREAD

**Issue by csjtx1021** [D-X-Y/AutoDL-Projects#68]
Hi, 

Nice project! 

Would you like to provide the search log files of 10 different searching algorithms in your NAS-Bench-201 paper? For example, would you like to provide the number of architectures evaluated for each search algorithm？

Thanks very much.

Best,

Jiaxu

**Comment by D-X-Y** [comment]
Please see the log here: https://drive.google.com/open?id=1eAgLZQAViP3r6dA0_ZOOGG9zPLXhGwXi

This is the original log and checkpoints. Sorry I did not have enough time to organize them well.

**Comment by csjtx1021** [comment]
Thanks a lot！
