### ISSUE TITLE
NAS-Bench 201 Benchmark Results are not consistent with paper

### ISSUE THREAD

**Issue by Jxu-Thu** [D-X-Y/AutoDL-Projects#70]
Hi, Thanks for your nice code!
I am a beginner. I want to reproduce the benchmark results of RSPS in Nas-Bench 201.
I follow the data settings as the requirement and run 

------
CUDA_VISIBLE_DEVICES=0 bash ./scripts-search/algos/RANDOM-NAS.sh cifar10 1 -1
-----
I find that when BN=0, my result is much higher than the results in paper and when BN=1, my result is much lower (about 5 points) than the results in paper. What is the differences?

And the codes run the RSPS with 250 epochs but the results of paper are described as follows:

"We report the mean and std of 500 runs for RS,
REA, REINFORCE, and BOHB and of 3 runs for RSPS, DARTS, GDAS, SETN, and ENAS."

Here 3 runs means just 3 epochs? or run the codes three times and report the mean and variance?

**Comment by D-X-Y** [comment]
3 runs means we run 3 times, where each time has 250 epochs. (Run the codes three times and report mean and variance).

BN=0 is indeed much better than BN=1, which has been discussed in the appendix and table 5.

**Comment by Jxu-Thu** [comment]
Thanks for the quick and nice reply!

**Comment by D-X-Y** [comment]
Please feel free to reopen it if you have more questions.
