### ISSUE TITLE
budget is not used in BOHB worker

### ISSUE THREAD

**Issue by aaronkl** [D-X-Y/AutoDL-Projects#71]
The budget in the compute function of the BOHB worker is not used. https://github.com/D-X-Y/AutoDL-Projects/blob/967a000a33da12d1b10321a03702bdfdb7eb1130/exps/algos/BOHB.py#L80
 If I am not mistaken, this will lead to BOHB evaluating every architecture on the full budget/max number of epochs, which means it cannot leverage the evaluation on smaller budgets and reduces it to perform standard Bayesian optimization.

**Comment by D-X-Y** [comment]
@aaronkl , You are right! The budget in BOHB is not used. I always want to leverage BOHB's ability to use smaller budgets, but did not find the correct way to implement it. Would you mind providing some suggestions?

**Comment by aaronkl** [comment]
If I understood correctly each architecture was evaluated for 12 epochs and one can specify the epoch in `self._nas_bench.get_more_info()`? 
So you could just return `self._nas_bench.get_more_info(arch_index, self._dataname, budget-1, True, True)` and set `min_budget=1, max_budget=12` in the  BOHB constructor

**Comment by D-X-Y** [comment]
I see. I will have a try. In this way, can I also control the maximum time used in BOHB? When compare RS, BOHB, REA, I hope to compare their results within a maximum time budget.

**Comment by aaronkl** [comment]
Unfortunately no, you can only control the total number of iterations (Hyperband brackets) of BOHB (it's the parameter n_iterations in the run() function).

**Comment by D-X-Y** [comment]
@aaronkl What if I do something like this: https://github.com/D-X-Y/AutoDL-Projects/blob/master/exps/algos/BOHB.py#L84 ? In short, I collect and accumulate the current time cost, if it is larger than the total time budget, then I disable the compute function.
Is this ok to constraint the time?

**Comment by aaronkl** [comment]
I don't think that works. It would continue running BOHB and just return 100 percent validation error to the optimizer. 

Here is what I would do:
You can estimate the average time BOHB spends per iteration, which, in your case, is roughly 6 times the average runtime of an architecture and then set the number of iterations accordingly. For example, if, on average, an architecture requires 100 seconds (this number is totally made up) to train for 200 epochs, than BOHB requires approximately 600 seconds per iteration. If you set it to 5 iterations, it will take around 3000 seconds. Obviously this is sensitive to stragglers - architectures that take much longer than others - but I don't think that is a big issue on your benchmark. BOHB returns you the optimization trajectory (the best configurations after each timestep) and you can then just trim this trajectory to the specific time budget.

**Comment by D-X-Y** [comment]
Thanks for your help and answer. I have updated a revised version of BOHB: https://github.com/D-X-Y/AutoDL-Projects/blob/master/exps/algos-v2/bohb.py :)
