### ISSUE TITLE
Search on the imagenet

### ISSUE THREAD

**Issue by jianxiangm** [D-X-Y/AutoDL-Projects#75]
Hi, I wanted to search the network directly on the imagenet1k with GDAS or STEN, but i found it's easy to OOM when searching, so the batchsize was only set to small one like 8, and the training is slow. I just wonder if these methods are not suitable for direct searching on the big datasets?

**Comment by D-X-Y** [comment]
I have tried to directly apply GDAS on ImageNet. It depends on the proxy model, batch size, and devices.
Would you mind to share more information w.r.t. the super model and the machine?

**Comment by jianxiangm** [comment]
> I have tried to directly apply GDAS on ImageNet. It depends on the proxy model, batch size, and devices.
> Would you mind to share more information w.r.t. the super model and the machine?

I just used the script `./scripts-search/NASNet-space-search-by-GDAS.sh`, i.e., searching on the NASNet search space, on the NVIDIA V100 32GB, with batchsize=4 (8 will lead to OOM), and the model config is like:
```conf
{
  "super_type"      : ["str",  "nasnet-super"],
  "name"            : ["str",  "GDAS"],
  "C"               : ["int",  "32"  ],
  "N"               : ["int",  "4"  ],
  "steps"           : ["int",  "4"  ],
  "multiplier"      : ["int",  "4"  ],
  "stem_multiplier" : ["int",  "3"  ]
}
```

**Comment by D-X-Y** [comment]
That would cause a lot of GPU memory, as the model is designed for CIFAR, where the input is 32x32.. If you apply it to ImageNet (input is usually 224x224), the feature maps will be very large. You should modify the network to adjust for ImageNet (for example use MobileNet-V2 search space, not supported yet).

**Comment by jianxiangm** [comment]
Thanks for your advice! As you said, should I modify the `search_model_gdas_nasnet.py` and corresponding search cell definition to  adjust for ImageNet? And are there some references for imagenet search space now as far as you know?

**Comment by D-X-Y** [comment]
For cell-based search space on ImageNet, you can refer to this one (https://github.com/D-X-Y/AutoDL-Projects/blob/master/lib/nas_infer_model/DXYs/ImageNet.py). You can also use the search space created by tuning the kernel size and expansion ratio of MobileNet-V2.
