### ISSUE TITLE
ImageNet16-120 dataset prep

### ISSUE THREAD

**Issue by abduallahmohamed** [D-X-Y/AutoDL-Projects#77]
Hi, 

I'm running `. /scripts-search/NAS-Bench-201/train-a-net.sh ` to train a found cell.
And I do have $TORCH_HOME/ILSVRC2012 data ready. 
I also ran this prep script` ./scripts/prepare.sh`
But I do encountered the following error:

![image](https://user-images.githubusercontent.com/22107547/83596870-6121c000-a52b-11ea-9390-06c9531fa33c.png)

Any resolution? 

Best

**Comment by D-X-Y** [comment]
ImageNet16-12 is not ILSVRC2012, while it is a subset of resized version of ImageNet.
My apologies. I should emphasize it in the README: https://github.com/D-X-Y/AutoDL-Projects/blob/master/docs/NAS-Bench-201.md#preparation-and-download . Please see the last sentence of "Preparation and Download", I share the data of ImageNet16-12 on Google Drive, and if you download and put it `ImageNet16` into $TORCH_HOME/cifar.python. You should be able to run

**Comment by abduallahmohamed** [comment]
Thanks!!!

**Comment by hafizuriu** [comment]
> ImageNet16-12 is not ILSVRC2012, while it is a subset of resized version of ImageNet. My apologies. I should emphasize it in the README: https://github.com/D-X-Y/AutoDL-Projects/blob/master/docs/NAS-Bench-201.md#preparation-and-download . Please see the last sentence of "Preparation and Download", I share the data of ImageNet16-12 on Google Drive, and if you download and put it `ImageNet16` into $TORCH_HOME/cifar.python. You should be able to run

I can't find **_imagenet16-120_** dataset in your repo. Could you please help me to find out the dataset?

**Comment by D-X-Y** [comment]
Can you access this link: https://drive.google.com/drive/folders/1T3UIyZXUhMmIuJLOBMIYKAsJknAtrrO4 and download ImageNet16?

**Comment by hafizuriu** [comment]
Thank you so much for your prompt response.
Could you please guide me on how I can read the dataset?

Best,
Hafizur

**Comment by D-X-Y** [comment]
You can have a look at this function: https://github.com/D-X-Y/AutoDL-Projects/blob/main/xautodl/datasets/get_dataset_with_transform.py#L99-L130

call `get_datasets("ImageNet16-120", path_to_the_data, -1)`, and you will get the dataset object

**Comment by hafizuriu** [comment]
Thank you so much.

**Comment by zhongjiachen1** [comment]
hi，this link: https://drive.google.com/drive/folders/1T3UIyZXUhMmIuJLOBMIYKAsJknAtrrO4, This link is no longer accessible. Has it been moved to the recycle bin? Could you share a new link again? I really need it, thanks

**Comment by D-X-Y** [comment]
@zhongjiachen1 it is back now, sorry for mis-deleting them

**Comment by zhongjiachen1** [comment]
Thank you very much for your help. I am now able to access it successfully. Best wishes.
