### ISSUE TITLE
Examples using image data from a datagenerator

### ISSUE THREAD

**Issue by cibic89** [D-X-Y/AutoDL-Projects#80]
Hi,

Really good work here!
I was wondering there are any examples with custom problems to solve as in with my own image data?

Thanks,
George

**Comment by D-X-Y** [comment]
A short answer is no, and we can add it in future. If you want to use your own data, you add add it at here: https://github.com/D-X-Y/AutoDL-Projects/blob/master/lib/datasets/get_dataset_with_transform.py#L213 by defining your own data loader.

**Comment by cibic89** [comment]
Appreciate the swift reply. Thank you for shedding light on this.
Are you looking for a contributor by any chance?

**Comment by D-X-Y** [comment]
Yes, it is welcome to contribute PR to this repo!

Please feel free to re-open this issue if you have any questions.
