### ISSUE TITLE
[NAS-Bench-201] Re-upload benchmark data to other places than Google Drive

### ISSUE THREAD

**Issue by johsnows** [D-X-Y/AutoDL-Projects#86]
请问可以把所有训练信息的200g文件传到百度网盘上嘛，国内google drive下载经常下到一半就 会网络错误，多谢了。

**Comment by D-X-Y** [comment]
好的，我会尽快上传到百度网盘。

**Comment by johsnows** [comment]
您好，请问是否上传成功了？尝试挺多办法了，国内下载google drive 226g文件确实太难了

**Comment by D-X-Y** [comment]
你好，因为我现在在美国，上传百度网盘也是非常慢，试了几次都没成功；我打算将训练信息的200g文件 split成多个小文件，上传到google drive，你看这样你方便下载么？

**Comment by johsnows** [comment]
好的，这样也会方便许多，多谢~

**Comment by johsnows** [comment]
另外有一个问题是，请问这个226g的文件 是包含了每个网络不同epoch下的weight嘛？

**Comment by D-X-Y** [comment]
没有，仅包含了最后一个epoch的weights。

**Comment by D-X-Y** [comment]
@johsnows 我已经split好了data，正在上传到（https://drive.google.com/drive/folders/17S2Xg_rVkUul4KuJdq0WaWoUuDbo8ZKB?usp=sharing），每个split 30G，你方便试一下能下载么？

**Comment by D-X-Y** [comment]
@johsnows Sorry for the late reply. I have re-uploaded all the benchmark data including weights to Baidu-Pan, please see more details in https://github.com/D-X-Y/NATS-Bench#preparation-and-download
