### ISSUE TITLE
How to get the model of the same topology but different sizes?

### ISSUE THREAD

**Issue by LicharYuan** [D-X-Y/AutoDL-Projects#94]
Hi, thank you for this benchmark. 

Since I have more interest in the model size which is add in NATS-Bench, 
How can i get the maximum number of models with the same topology but different size? 

Thanks ~~~

**Comment by LicharYuan** [comment]
oh, i found the size search space is under same topology...

**Comment by D-X-Y** [comment]
Cool~ Let me know if you have other questions :)
