### ISSUE TITLE
[NATS-Bench] How to get the Top-N % models? 

### ISSUE THREAD

**Issue by LicharYuan** [D-X-Y/AutoDL-Projects#95]
This repo provides a very good api to query models,

 I wonder is there easier ways to get top-1 % models in Nats-Bench (Size) except traverse all index?

**Comment by D-X-Y** [comment]
Thanks a lot for your interest.
Ideally, we can preprocess all accuracies and save top-1 in the benchmark files. In practice, as there are some conditions to obtain the top-1%, for example, top-1% on CIFAR-10 w.r.t. the mean accuracy, top-1% on CIFAR-10 w.r.t. the mean test loss.
There could be multiple top-1%, and I cannot give an assumption for what the users want. Therefore, we did not provide such top-1% models, and it is better to do on the user side.

**Comment by LicharYuan** [comment]
Gotta, Thank  your suggestions :)
